name: Release to PyPI

on:
  release:
    types: [created]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    needs: [lint, test]
    environment:
      name: pypi
      url: https://pypi.org/p/requests-pro
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync --locked --all-extras --dev
      - name: Build package
        run: uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
